apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
  namespace: jitsi
spec:
  ports:
  - name: "http"
    port: 81
    targetPort: 81
  - name: "https"
    port: 443
    targetPort: 443
  selector:
    k8s-app: jitsi
